### ISSUE TITLE
希望可以查询到对应玩家的冒险等级

### ISSUE THREAD

**Issue by Haku247** [babalae/genshin-info#3]

**Comment by huiyadanli** [comment]
米游社貌似不能看到其他玩家的冒险等级的吧。

接口中也没有相关的返回。

**Comment by Haku247** [comment]
手机app有的，我截图给你看一下

随便找了一个人物。名字下面就是等级。

详情页面也有
[cid:0D4D2749-171D-4FA7-920C-BAE8B3804FE9-L0-001][cid:13FA54B2-91E5-44B3-A24B-EA8DDF09A897-L0-001]

在 2021年2月28日，15:31，辉鸭蛋 <notifications@github.com> 写道：

﻿

米游社貌似不能看到其他玩家的冒险等级的吧。

接口中也没有相关的返回。

**Comment by ICMYS** [comment]
> 手机app有的，我截图给你看一下 随便找了一个人物。名字下面就是等级。 详情页面也有 [cid:0D4D2749-171D-4FA7-920C-BAE8B3804FE9-L0-001][cid:13FA54B2-91E5-44B3-A24B-EA8DDF09A897-L0-001] 在 2021年2月28日，15:31，辉鸭蛋 <notifications@github.com> 写道： ﻿ 米游社貌似不能看到其他玩家的冒险等级的吧。 接口中也没有相关的返回。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbabalae%2Fgenshin-info%2Fissues%2F3%23issuecomment-787404253&data=04%7C01%7C%7Ca1fea8bce83a4e60f84608d8dbb270b4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637500906752810245%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=KbKVoCI0n9L2CxIhiHN%2Bzc7SbNs6a2B%2B%2BNiQh%2BuwS0w%3D&reserved=0>, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAE2M7BLR5FVBH56IWPNBYRTTBHPK5ANCNFSM4YJRBWTA&data=04%7C01%7C%7Ca1fea8bce83a4e60f84608d8dbb270b4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637500906752810245%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=PRlrIcVCeJvifmqIwozb8IXfBsZwfXGy1lU%2FghkKyX0%3D&reserved=0>.

查询冒险等级和昵称所使用参数的是米游社ID而不是游戏内的UID，然而问题没有API可以通过UID查询米游社ID
API: https://api-takumi.mihoyo.com/game_record/card/wapi/getGameRecordCard?uid=(米游社ID)
