### ISSUE TITLE
大佬，在线查询和书签都失效了

### ISSUE THREAD

**Issue by 1055169799** [babalae/genshin-info#6]
是不是因为米哈游的论坛地址从https://bbs.mihoyo.com/ys/ 更换为https://www.miyoushe.com/ys/ 了？

**Comment by huiyadanli** [comment]
在线查询 很久之前就不维护了。

书签地址改过了，应该还能用

**Comment by 1055169799** [comment]
抱歉打扰了，不知道是不是我这边的问题，我从两个网站上拖拽到书签栏的书签都是无效的

https://babalae.netlify.app/
![image](https://user-images.githubusercontent.com/41286675/217467218-a71094cf-12d5-4cdc-ab14-a8b459e3b5cf.png)

https://babalae.github.io/bookmarklet/
![image](https://user-images.githubusercontent.com/41286675/217467298-7c736a3f-0eb3-4808-9bd9-a0eddbba8bda.png)

**Comment by huiyadanli** [comment]
![image](https://user-images.githubusercontent.com/15783049/217519531-298443e8-c653-4a74-ac0c-f77eb35401ad.png)

我测试没有问题，你重新登录下再试试。

**Comment by 1055169799** [comment]
> ![image](https://user-images.githubusercontent.com/15783049/217519531-298443e8-c653-4a74-ac0c-f77eb35401ad.png)
> 
> 我测试没有问题，你重新登录下再试试。

好的谢谢，退出账号之后重新登陆可以了，大概是cookie过期了

**Comment by 1055169799** [comment]
> > ![image](https://user-images.githubusercontent.com/15783049/217519531-298443e8-c653-4a74-ac0c-f77eb35401ad.png)
> > 
> > 我测试没有问题，你重新登录下再试试。
> 
> 好的谢谢，退出账号之后重新登陆可以了，大概是cookie过期了

刚试了一下，谷歌浏览器和Edge上可以用，放到360浏览器里，重登账号和清除上网痕迹之后再登还是查不到，有点奇怪了
